/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.math.graphic.forms.conversion;

import ec.edu.espe.math.conversion.Conversion;
import ec.edu.espe.math.conversion.multiples.DecameterMeter;
import ec.edu.espe.math.conversion.multiples.HectometerDecameter;
import ec.edu.espe.math.conversion.multiples.KilometerHectometer;
import ec.edu.espe.math.conversion.submultiples.CentimeterMillimeter;
import ec.edu.espe.math.conversion.submultiples.DecimeterCentimeter;
import ec.edu.espe.math.conversion.submultiples.MeterDecimeter;
import ec.edu.espe.math.graphic.forms.shapes2d.*;
import ec.edu.espe.math.geometry.shapes.circunferences.Circle;
import ec.edu.espe.math.graphic.forms.*;
import ec.edu.espe.math.graphic.forms.constant.ConversionCatalog;
import ec.edu.espe.math.graphic.forms.constant.ShapeCatalog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Cazaesclavas
 */
public class ConversionForm extends javax.swing.JFrame {

    ShapeCatalog shapes = new ShapeCatalog();
    ConversionCatalog units = new ConversionCatalog();
    
    DecameterMeter damM = null;
    HectometerDecameter hmDam = null;
    KilometerHectometer kmHm = null;
    
    CentimeterMillimeter cmMm = null;
    DecimeterCentimeter dmCm = null;
    MeterDecimeter mDm = null;
    /**
     * Creates new form MainMenu
     */
    public ConversionForm(String _nameShape) {
        initComponents();
        nameShape.setText(_nameShape);
        selectUnit();
    }
    
    public void selectUnit(){
        
        unitFromSelect.removeAllItems();
        unitFromSelect.addItem("[u]");
        unitFromSelect.addItem(units.MILLIMETER);
        unitFromSelect.addItem(units.CENTIMETER);
        unitFromSelect.addItem(units.DECIMETER);
        unitFromSelect.addItem(units.METER);
        unitFromSelect.addItem(units.DECAMETER);
        unitFromSelect.addItem(units.HECTOMETER);
        unitFromSelect.addItem(units.KILOMETER);
        
        unitToSelect.removeAllItems();
        unitToSelect.addItem("[u]");
        unitToSelect.addItem(units.MILLIMETER);
        unitToSelect.addItem(units.CENTIMETER);
        unitToSelect.addItem(units.DECIMETER);
        unitToSelect.addItem(units.METER);
        unitToSelect.addItem(units.DECAMETER);
        unitToSelect.addItem(units.HECTOMETER);
        unitToSelect.addItem(units.KILOMETER);
        
        unitToSelect.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    String search =  unitFromSelect.getSelectedItem().toString() + unitToSelect.getSelectedItem().toString();
                    System.out.println(search);
                    conversionSelect(search);
                }catch(Exception er){}
                
            }
        });
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        nameShape = new javax.swing.JLabel();
        loginButton1 = new javax.swing.JButton();
        solutionConvertValue = new javax.swing.JLabel();
        radioValue = new javax.swing.JTextField();
        solutionTypeConversion = new javax.swing.JLabel();
        unitToSelect = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        unitFromSelect = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(85, 96, 128));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 350));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/math/graphic/images/logoGeometry.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(38, 185, 154));
        jSeparator1.setForeground(new java.awt.Color(38, 185, 154));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 185, 154));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Input");

        nameShape.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameShape.setForeground(new java.awt.Color(38, 185, 154));
        nameShape.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameShape.setText("Input");

        loginButton1.setText("Close");
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });

        solutionConvertValue.setForeground(new java.awt.Color(255, 255, 255));
        solutionConvertValue.setText("Waiting...");

        solutionTypeConversion.setForeground(new java.awt.Color(255, 255, 255));
        solutionTypeConversion.setText("Waiting...");

        unitToSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 185, 154));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Output");

        unitFromSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 185, 154));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("from:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 185, 154));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("to:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameShape, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solutionTypeConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unitFromSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unitToSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(solutionConvertValue, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(radioValue)))
                    .addComponent(loginButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameShape)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(radioValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitFromSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unitToSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solutionConvertValue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addComponent(solutionTypeConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_loginButton1ActionPerformed

        public void conversionSelect(String search){
            String unit = unitToSelect.getSelectedItem().toString();
        switch (search) {
            //multiples
            case "DecameterMeter":
                damM = new DecameterMeter(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion Dam -> m");
                solutionConvertValue.setText("Conversion: "+damM.calculate() + " ["+unit+"]");
                break;
            case "HectometerDecameter":
                hmDam = new HectometerDecameter(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion Hm -> Dam");
                solutionConvertValue.setText("Conversion: "+hmDam.calculate() + " ["+unit+"]");
                break;
            case "KilometerHectometer":
                kmHm = new KilometerHectometer(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion Km -> Hm");
                solutionConvertValue.setText("Conversion: "+kmHm.calculate() + " ["+unit+"]");
                break;
            //submultiples
            case "CentimeterMillimeter":
                cmMm = new CentimeterMillimeter(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion cm -> mm");
                solutionConvertValue.setText("Conversion: "+cmMm.calculate() + " ["+unit+"]");
                break;
            case "DecimeterCentimeter":
                dmCm = new DecimeterCentimeter(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion dm -> cm");
                solutionConvertValue.setText("Conversion: "+dmCm.calculate() + " ["+unit+"]");
                break;
            case "MeterDecimeter":
                mDm = new MeterDecimeter(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Direct Conversion m -> dm");
                solutionConvertValue.setText("Conversion: "+mDm.calculate() + " ["+unit+"]");
                break;
            case "KilometerMeter":
                kmHm = new KilometerHectometer(Float.parseFloat(radioValue.getText()));
                solutionTypeConversion.setText("Indirect Conversion Km -> m");
                solutionConvertValue.setText("Conversion: "+mDm.calculate() + " ["+unit+"]");
                break;
            
            default:
                JOptionPane.showMessageDialog(null, "Conversion under construction.");
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionForm("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton1;
    private javax.swing.JLabel nameShape;
    private javax.swing.JTextField radioValue;
    private javax.swing.JLabel solutionConvertValue;
    private javax.swing.JLabel solutionTypeConversion;
    private javax.swing.JComboBox<String> unitFromSelect;
    private javax.swing.JComboBox<String> unitToSelect;
    // End of variables declaration//GEN-END:variables
}
